version: "3.9"

services:
  webservice:
    build: ./webservice
    container_name: "webservice"
    ports:
      - "5000:5000"
    networks:
      - app-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]  # Specify GPU capabilities

  discord_bot:
    build: ./discord_bot
    container_name: "discord_bot"
    ports:
      - "5001:5000"
    networks:
      - app-network
    environment:
      - WEBSERVICE_URL=http://webservice:5000  # Updated to use container name as hostname

networks:
  app-network:
    driver: bridge
